
- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: "/var/lib/jenkins/workspace/k8s-pipeline/"
    dest_path: "/home/ansadmin"
    config_file_dest_path: "/home"
  tasks:
    - name: copying files with playbook
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansadmin
        group: ansadmin
        mode: 0777
    - name: build image
      become: true
      shell:
        cmd: ./gradlew jibDockerBuild
    - name: edit env path 
      shell: "export PATH=$PATH:/usr/local/bin"
    - name: Run `docker-compose up` again
      community.docker.docker_compose:
        project_src: .
        build: false
      register: output



#  add this command to edit path variable... export PATH=$PATH:/usr/local/bin


    # - name: pull docker image
    #   become: true
    #   shell:
    #     "docker pull joeting91/nuvalence"