
- name: Ansible Copy Local to Remote
  hosts: "{{hosts}}"
  vars:
    src_path: "/var/lib/jenkins/workspace/k8s-pipeline/"
    dest_path: "/home/ansadmin"
    config_file_dest_path: "/home"
  tasks:
    - name: copying files with playbook
      become: true
      copy:
        src: "{{ src_path }}"
        dest: "{{ dest_path }}"
        owner: ansadmin
        group: ansadmin
        mode: 0644
    - name: build image
      become: true
      shell:
        chdir: /home/ansadmin/k8s-pipeline
        cmd: ./gradlew jibDockerBuild
    - name: start containers
      become: true
      shell:
        chdir: /home/ansadmin/k8s-pipeline
        cmd: docker-compose up




    # - name: pull docker image
    #   become: true
    #   shell:
    #     "docker pull joeting91/nuvalence"